"""users +email

Revision ID: 2a9b30b24331
Revises: b79b60b852ff
Create Date: 2026-06-15 22:01:51.634907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9b30b24331'
down_revision: Union[str, Sequence[str], None] = 'b79b60b852ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
