"""Chat without title

Revision ID: 2d4ab25dad78
Revises: 86ff36162ceb
Create Date: 2026-06-27 16:14:59.285916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4ab25dad78'
down_revision: Union[str, Sequence[str], None] = '86ff36162ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
