"""settings for_user->user_id

Revision ID: 5d460d2e8e0e
Revises: 724b645e3d8f
Create Date: 2026-06-18 18:03:02.019431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d460d2e8e0e'
down_revision: Union[str, Sequence[str], None] = '724b645e3d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'settings', ['user_id'])
    op.create_foreign_key(None, 'settings', 'users', ['user_id'], ['id'])
    op.drop_column('settings', 'for_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('for_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_constraint(None, 'settings', type_='unique')
    op.drop_column('settings', 'user_id')
    # ### end Alembic commands ###
