"""User online & last_online

Revision ID: d9b5ee2229e0
Revises: 2d4ab25dad78
Create Date: 2026-06-29 13:41:53.061908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b5ee2229e0'
down_revision: Union[str, Sequence[str], None] = '2d4ab25dad78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('online', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_online', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_online')
    op.drop_column('users', 'online')
    # ### end Alembic commands ###
